#!/bin/bash
#
#		--------------- darktheme ---------------
#
#		This script can be used both to manually
#		set kde desktop theme to breeze dark or 
#		to specify the time when it will be set
#		automatically.
#


CMD_NAME="darktheme"


# Source global variables and functions
source globals.sh


# If no arguments are provided the theme is changed to breeze dark. TODO: move org.kde.breezedark.desktop into a variable inside a config file and make it editable using this command
[[ -z $1 ]] && { lookandfeeltool -a 'org.kde.breezedark.desktop' &> /dev/null; exit 0; }

# If argument set is provided, dark theme activation time is set.
[[ -n $1 && -n $2 ]] && {

	# Check argument
	[[ $1 == "set" ]] || { echo "Invalid command: $1"; exit 0; }

	L_TIME=$(get_time $LIGHTTHEME_TIMER)

	# If inserted date is equal to lighttheme date, throw an error
	[[ $2 != $L_TIME ]] || { echo "Dark theme activation time cannot be the same as lighttheme"; exit 0; }

	# Set light theme activation time
	set_time $DARKTHEME_TIMER $2 || exit 1

	echo "Dark theme activation time successfully set to $2!"
	exit 0
}
