#!/bin/bash
#
#		--------------- lighttheme ---------------
#
#		This script can be used both to manually
#		set kde desktop theme to breeze (light) or 
#		to specify the time when it will be set
#		automatically.
#


CMD_NAME="lighttheme"
DARKTHEME_TIMER="/home/${USER}/.config/systemd/user/darktheme.timer"
LIGHTTHEME_TIMER="/home/${USER}/.config/systemd/user/lighttheme.timer"


#
#	Create a file and all parent directories.
#
#	SYNTAX:		mkfile PATH
#
mkfile() {

	# Argument check
	[[ -z $1 ]] && { echo "$(basename $0): missing arguments"; return 1; }
	
	local filename=$(basename $TIMINGS)
	local folder=${1%$filename}

	# Create folders
	mkdir -p "$folder"

	# Error checking
	local ret_value=$?
	[[ $ret_value != 0 ]] && return $ret_value

	# Create file
	touch "$1"

	# Error checking
	ret_value=$?
	[[ $ret_value != 0 ]] && return $ret_value

	return 0
}


#
#	Get theme activation time.
#
#	SYNTAX:		get_time PATH_TO_TIMER
#
get_time() {

	# Argument check
	[[ -z $1 ]] && { echo "missing arguments"; return 1; }

	# Check if file ($1) is either $DARKTHEME_TIMER or $LIGHTTHEME_TIMER.
	[[ $1 == $DARKTHEME_TIMER || $1 == $LIGHTTHEME_TIMER ]] || { 
		echo "theme activation time can be retrieved only by either $LIGHTTHEME_TIMER or $DARKTHEME_TIMER"; 
		return 1;
	}

	# Check if file ($1) exists. If not settheme is not installed.
	[[ -e $1 ]] || { echo "$1 doesn't exist. You might have to run install.sh."; return 1; }

	# Dark theme activation time
	D_TIME=$(sed -n '/OnCalendar/p' $1 | \
			 grep -oE "([01][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]")

	return 0
}


#
#	Set theme activation time.
#
#	SYNTAX:		set_time PATH_TO_TIMER TIME
#
set_time() {

	# Argument check
	[[ -z $1 || -z $2 ]] && { echo "missing arguments"; return 1; }

	# Check if file ($1) is either $DARKTHEME_TIMER or $LIGHTTHEME_TIMER.
	[[ $1 == $DARKTHEME_TIMER || $1 == $LIGHTTHEME_TIMER ]] || { 
		echo "theme activation time can be retrieved only by either $LIGHTTHEME_TIMER or $DARKTHEME_TIMER"; 
		return 1;
	}
	
	# Check if file ($1) exists. If not settheme is not installed.
	[[ -e $1 ]] || { echo "$1 doesn't exist. You might have to run install.sh."; return 1; }

	# Check good date format
	[[ $2 =~ ^[0-9]{2}:[0-9]{2}:[0-9]{2}$ ]] || { echo "$2 is not a valid date format. Use instead HH:MM:SS"; return 1; }

	# Check if date is valid
	[[ $2 =~ ^([01][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]$ ]] || { echo "Date not valid. It can range from 00:00:00 to 23:59:59"; return 1; }

	# Replace time in .timer file
	sed -iE 's/^OnCalendar=\*-\*-\* ([01][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]$/OnCalendar=*-*-* 15:00:00/' $1

	return 0
}


# If no arguments are provided the theme is changed to breeze light. TODO: move org.kde.breeze.desktop into a variable inside a config file and make it editable using this command
[[ -z $1 ]] && { lookandfeeltool -a 'org.kde.breeze.desktop' &> /dev/null; exit 0; }

# If argument set is provided, light theme activation time is set.
[[ -n $1 && -n $2 ]] && {

	# Check argument
	[[ $1 == "set" ]] || { echo "invalid command: $1"; exit 0; }

	get_time $DARKTHEME_TIMER

	# If inserted date is equal to darktheme date, throw an error
	[[ $2 != $D_TIME ]] || { echo "lighttheme activation time cannot be the same as darktheme"; exit 0; }

	# Set light theme activation time
	set_time $LIGHTTHEME_TIMER $2

	echo "light theme activation time successfully set to $2!"

}
