#!/bin/bash
#
#		--------------- onstartup ---------------
#
#		This file is executed right after reboot by 
#		cron (take a look at /etc/cron.d/).
#
#		If the current time is in light theme range
#		the theme is set to light and viceversa.
#


# Default values
S_TIME=$(date -d"00:00:00" +%s) # Start of the day
E_TIME=$(date -d"23:59:59" +%s) # End of the day
L_TIME=$(date -d"07:00:00" +%s) # Light theme activation time
D_TIME=$(date -d"19:00:00" +%s) # Dark theme activation time

# Commands to change theme
SET_DARK="/usr/local/bin/darktheme"
SET_LIGHT="/usr/local/bin/lighttheme"

# Custom values
TIMINGS="/home/${USER}/.local/share/settheme/timings"

# If a custom value is set it will overwrite the defaults
[[ ! -r $TIMINGS ]] || . "$TIMINGS"

# Current time
current_time=$(date +%s)

[[ $L_TIME < $D_TIME ]] && {

	# If 00:00:00 <= current_time < light_time or dark_time <= current_time <= 23:59:59
	[[ ($S_TIME <= $current_time && $L_TIME > $current_time) || ($D_TIME <= $current_time && $E_TIME >= $current_time) ]] && $SET_DARK

	# If light_time <= current_time < dark_time
	[[ $L_TIME <= $current_time && $D_TIME > $current_time ]] && $SET_LIGHT

}

[[ $D_TIME < $L_TIME ]] && {

	# If 00:00:00 <= current_time < dark_time or light_time <= current_time <= 23:59:59
	[[ ($S_TIME <= $current_time && $D_TIME > $current_time) || ($L_TIME <= $current_time && $E_TIME >= $current_time) ]] && $SET_LIGHT

	# If dar_time <= current_time < light_time
	[[ $D_TIME <= $current_time && $L_TIME > $current_time ]] && $SET_DARK

}
